# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Backend Docker Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        working-directory: backend

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: backend

    - name: Build with Gradle
      run: ./gradlew build -x test
      working-directory: backend

    - name: Debug - List files in build/libs
      run: |
        ls -la build/libs
        ls -la build/libs/*.jar
        ls -la build/libs/*SNAPSHOT.jar
      working-directory: backend

    - name: Copy JAR file
      run: cp build/libs/*SNAPSHOT.jar backend.jar
      working-directory: backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this secret in your repo settings
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set this secret in your repo settings

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend  # Path to your Dockerfile and application
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/zw_back:latest
          ${{ secrets.DOCKER_USERNAME }}/zw_back:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

    - name: Verify Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/zw_back:latest
        docker images
